[package]
name = "mjpeg-sys"
version = "0.1.0"
authors = ["Dave Hylands <dhylands@gmail.com>"]
build = "build.rs"

[dependencies]
libc = "0.2"
quirc-sys = { path = "../quirc-sys", version = "0.1" }

[build-dependencies]
gcc = "0.3"
